### ISSUE TITLE
Installer.sh Does not start 

### ISSUE THREAD

**Issue by nickelz34** [Alexander88207/RTL8812au-Installer#1]
Using Kali Linux everything is updated . Looking at your code i believe it is either unfinished or needs to be cleaned up still . Looking at it with `cat -vet Installer.sh` I can see alot of tabbing and other errors.

Really wanted to try this one out maybe its my own error , if so maybe you can chime in on a idea or two to get this running ?

**Comment by Alexander88207** [comment]
You only have to execute the command `bash Installer.sh` in the folder.

If this does not work, make sure that you have installed the package "dialog".

![gif](https://user-images.githubusercontent.com/37543796/53186843-1e6ff900-3602-11e9-8784-54e7f831e373.gif)


Since Ubuntu is also based on debian, this should also work for you with the Ubuntu option.

**Comment by Alexander88207** [comment]
I'm closing this issue now, should it still persist the problem feel free to reopen this.
